### ISSUE TITLE
sparseGRM 

### ISSUE THREAD

**Issue by skoyamamd** [GeneticAnalysisinBiobanks/GRAB#10]
Thank you very much for developing GRAB framework.
When running GRAB.NullModel function, I am encountering the following error.
my GRM file contains part of individuals in pheno file (kinship > 0.01 etc).
 
```
library(GRAB)

pheno = data.frame(fread("pheno.txt", header=T))
pheno$pheno = as.factor(pheno$pheno)

grmfile = "tmp.king"
bgenfile = "chr22.bgen"

nmod = GRAB.NullModel(
  formula = pheno ~ sex + age ,
  data = pheno,
  subjData = pheno$sample,
  method = "POLMM",
  traitType = "binary",
  SparseGRMFile = grmfile,
  GenoFile = bgenfile
)
```

```
Sparse GRM is used when fitting a null model.Error in updateSparseGRM(SparseGRM, subjData) : 
  At least one of subjects is not in SparseGRM.
Calls: GRAB.NullModel -> setGRM -> updateSparseGRM
```

From this code, 
`  if(any(!is.element(subjData, ID1)))
    stop("At least one of subjects is not in SparseGRM.")
`

Do we have to have all the samples in Phenotype file in Sparse GRM?
Thank you for your advice.

Best

**Comment by WenjianBI** [comment]
You are right. All the samples in phenotype should be in Sparse GRM. The analysis requires genotype data, which can be used to make a Sparse GRM. Hence, I think it is reasonable that all samples in phenotype data are in Sparse GRM. In my opinion, if only phenotype data (no genotype data) is available for a subject, then it should be excluded when fitting a null model. 

BTW, for method of "POLMM", traitType cannot be "binary". Please check https://wenjianbi.github.io/grab.github.io/ for more details. 

Thanks,
Wenjian

**Comment by skoyamamd** [comment]
Dear Wenjian,

Thank you for your response! I tried Sparse GRM with all the individuals, but still, I encountered errors.
To run the program, I need to modify the code (SparseGRM.R) as follows.

```
tempGRM = rbind(tempGRM1, tempGRM2)
# tempGRM = tempGRM[-1*which(duplicated(tempGRM)),]
tempGRM = unique(tempGRM)
```

I assume that you are creating a data frame so that all samples are present in both ID1 and ID2 and removing duplicated rows here. But this line (`tempGRM = tempGRM[-1*which(duplicated(tempGRM)),]`) does not work well in my environment.

Would not this change the original behavior?

Thank you so much!

Satoshi
